### ISSUE TITLE
Demo for HeadlessToast freezes tab

### ISSUE THREAD

**Issue by nkmnz** [xiaoluoboding/vue-sonner#15]
Hi there, great project! I've noticed that the demo on https://vue-sonner.vercel.app/ completely freezes when you open the Headless example (very last on the page) and try to close it with the close button. Tested on both Brave and Chrome. All other close buttons seem to work fine!

**Comment by xiaoluoboding** [comment]
Get it. Thanks for report this issue.

**Comment by xiaoluoboding** [comment]
fixed #20
