### ISSUE TITLE
Demo site animation css missing

### ISSUE THREAD

**Issue by markthree** [xiaoluoboding/vue-sonner#16]
![动画](https://github.com/xiaoluoboding/vue-sonner/assets/36569518/18bb1e4c-a2f8-4a5a-a9cc-372dd1d8aaf8)

[vue-sonner.vercel.app](https://vue-sonner.vercel.app/) animation css missing

**Comment by xiaoluoboding** [comment]
Not reproduced

**Comment by markthree** [comment]
After I updated my browser, the animation appeared
