### ISSUE TITLE
Programatically dismiss custom toast

### ISSUE THREAD

**Issue by nuno-m** [xiaoluoboding/vue-sonner#18]
Looking at the [code implementation](https://github.com/xiaoluoboding/vue-sonner/blob/795dcfd16a1286530ce4b46e1cb89b4697d2d037/packages/state.ts#L74), the custom toast function doesn't return an `id`.
Is it possible to programatically dismiss a given custom toast without an ID?

Also, if I use the `toast.dismiss()` function to dismiss all active toasts, I'm getting a warning:
```js
const renderCustomToast = () => {
  toast.custom(shallowRef(MyToastComponent), { duration: Infinity })
}

const dismissToast = () => {
  toast.dismiss()
}
```

This triggers the following warning
```console
Vue warn]: Maximum recursive updates exceeded. 
This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself.
Possible sources include component template, render function, updated hook or watcher source function.
```

**Comment by xiaoluoboding** [comment]
fixed #20
