### ISSUE TITLE
Toast hover warning

### ISSUE THREAD

**Issue by frasza** [xiaoluoboding/vue-sonner#2]
Whenever I hover over rendered toast, warning appears in the console saying `Write operation failed: computed value is readonly`

![image](https://user-images.githubusercontent.com/22049682/228372346-4e8b2426-e3d3-48e7-a260-b6488b7ee7e8.png)

**Comment by xiaoluoboding** [comment]
@frasza Get it, I'm gonna fixed it.

**Comment by xiaoluoboding** [comment]
https://github.com/xiaoluoboding/vue-sonner/commit/c8adec18ba44629b367056385b071d6eb0a7fc37
