### ISSUE TITLE
Is there a way to set position for individual toasts?

### ISSUE THREAD

**Issue by AlejandroAkbal** [xiaoluoboding/vue-sonner#23]
e.g.

```vue
<Toaster position="top-center" />
```

```js
toast('This toast will be on bottom', {
      position: 'bottom-center'
})
```

**Comment by wobsoriano** [comment]
I think that breaks the purpose of stackable toasts, no?

**Comment by gsabater** [comment]
@wobsoriano Maybe, but it would be extremely useful.
I guess by your comment that it's not possible?

**Comment by kecoliva** [comment]
> I think that breaks the purpose of stackable toasts, no?

Not really; besides, the original sonnet itself [implements this](https://sonner.emilkowal.ski/toast#dynamic-position).

**Comment by wobsoriano** [comment]
Good catch @kecoliva. I actually forgot about that 😄
