### ISSUE TITLE
descriptionClassName not being applied

### ISSUE THREAD

**Issue by BayBreezy** [xiaoluoboding/vue-sonner#30]
Hello,

When I pass descriptionClassName to the toastOptions object, it does not get applied to the description text. I have this in my nuxt plugin

```ts
import { Toaster } from "vue-sonner";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("Toaster", {
    setup(props, ctx) {
      return () =>
        h(Toaster, {
          toastOptions: {
            className: "!bg-background !text-foreground !border-border",
            descriptionClassName: "!text-muted-foreground",
          },
          ...props,
          ...ctx.attrs,
        });
    },
  });
});
```

The className gets applied but when I check the browser elements, for the description, I see `undefined`

![image](https://github.com/xiaoluoboding/vue-sonner/assets/53905713/d18f2752-1995-4d47-9f34-8feeb8b267f5)

**Comment by sadeghbarati** [comment]
@BayBreezy 

it should be fixed in new release
