### ISSUE TITLE
toast.promise renders 3 toasts on resolve

### ISSUE THREAD

**Issue by warflash** [xiaoluoboding/vue-sonner#34]
Hey, really enjoying the package so far!
When switching over our existing toasts to this package I noticed that after a toast.promise resolves the promise there's 3 toasts instead of one success toast like this:
![image](https://github.com/xiaoluoboding/vue-sonner/assets/22006082/4f30cb11-1e3e-4d52-9f69-d8aa35b00720)

Reproduction: https://stackblitz.com/edit/github-zwebrm?file=plugins%2Fsonner.client.ts,package.json,app.vue,nuxt.config.ts

**Comment by xiaoluoboding** [comment]
Thank you for bringing this issue to my attention. I have reviewed the reproduction results and I will handle it as soon as possible.

**Comment by xiaoluoboding** [comment]
fixed #35

**Comment by BayBreezy** [comment]
Thanks for the fix
