### ISSUE TITLE
Everything is deleted after <Toaster />, and sometimes the toast() function works, sometimes not

### ISSUE THREAD

**Issue by idk-floppy** [xiaoluoboding/vue-sonner#61]
I have my vue app setup and I followed the instructions, but even if I just copy-paste the first example, the button is not there, and even if it is there (explained in next section), on click it says `Uncaught TypeError: toast is not a function` . Am I possibly missing something? 

When I add the <Toaster /> to my root, nothing happens, but if I register it as a component ( `app.component('Toaster', Toaster);` ), the toaster shows up, but my **entire** content is just disappeared (even the "give me a toast" button provided)
Noticed that if I put the <Toaster /> before anything, they disappear, but if I put it after anything, they will not disappear. It's like it deletes everything that comes after it.

Example:
```
<div>I will show up</div>
    <Toaster />
<div>I will NOT show up</div>
```

I'm using Vue 3.

I'm not sure what decides if the toast method works or not, but if I can get more info, I'll include it. My main problem/concern is the "everything disappears after <Toaster />" part.

**Comment by warflash** [comment]
Could you please share a working reproduction somewhere like [stackblitz](https://stackblitz.com/fork/github/vitejs/vite/tree/main/packages/create-vite/template-vue?file=index.html&terminal=dev)?

**Comment by idk-floppy** [comment]
I think I managed to replicate the problem after about 2 hours.
https://stackblitz.com/edit/vitejs-vite-tzbeke?file=index.html,src%2Fmain.js&terminal=dev

Here you can see that "hello" shows up, test and test 2 doesn't, and then hello 3 shows up again.

I had to play around to match my local, but I got it :D 

Hope it will be any useful, even if I messed something up and that's the reason why it's not working as intended.

**Comment by warflash** [comment]
@idk-floppy This is a vue package and component so you can't just add it straight into html. You need to register the components within vue's app. -> https://stackblitz.com/edit/vitejs-vite-cieu4q?file=src%2FApp.vue,index.html,src%2Fmain.js&terminal=dev

**Comment by idk-floppy** [comment]
I did register it as a component, and put it inside the div that the app is mounted to.

app.component, app.mount, and then the toaster component is inside the mounted div, so it is registered as a global component.

Thank you for your help!
