### ISSUE TITLE
ERROR - Dismiss not working

### ISSUE THREAD

**Issue by ishaiavrahami** [xiaoluoboding/vue-sonner#63]
The dissmiss function is not working and breaking the toaster. This is the code im running. Very simple.  
```
toast.dismiss(toastId)
```
and its returning 

Uncaught (in promise) Maximum recursive updates exceeded in component <Toaster>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

<img width="673" alt="Screenshot 2024-03-31 at 6 21 01 PM" src="https://github.com/xiaoluoboding/vue-sonner/assets/33962719/e12be321-f1ba-47e8-84ab-98df9d1862e4">

**Comment by ishaiavrahami** [comment]
@xiaoluoboding please see this has it breaks the code. New toasts WONT work

**Comment by Froelund** [comment]
I have this same issue 🖐️
Minor difference in my implementation, but the error is similar.
```
const toastId = toast('Event', { duration: 10000 });
toast.dismiss(toastId)
```

**Comment by ishaiavrahami** [comment]
@Froelund its ridiculous. i fixed this by emitting `emit('closeToast')` inside the component

**Comment by luanyata** [comment]
> @Froelund é ridículo, eu consertei isso emitindo `emit('closeToast')` dentro do componente

I'm having the same problem. I'm using Vue3's Composition API.

Could you give me an example of how you solved it? 
Thanks
