### ISSUE TITLE
Set Toast width

### ISSUE THREAD

**Issue by IVoyt** [xiaoluoboding/vue-sonner#82]
Hi. Thanks for the great plugin.

Can you add option or maybe it already exists but I can't find it. I want to set custom toast width. How can I do this?

**Comment by fdsssawe** [comment]
@IVoyt Hey. You can set custom width for the toast using toastOptions.

If you wont to keept it static for all toast, you can just create your <Toaster/> by importing it from the plugin, modify it using toastOptions, and when using it, import toaster from this file, not from the plugin, so :

```
<script setup lang="ts">
import { Toaster } from 'vue-sonner'
}>()

</script>
<template>
  <Toaster
      :toastOptions="{
        style :  { width: '150px' },
      }"
  />
</template>
```

For tailwind 

```
<script setup lang="ts">
import { Toaster } from 'vue-sonner'
}>()

</script>
<template>
  <Toaster
      :toastOptions="{
        unstyled: true,
        classes: {
          toast: 'w-[150px]',
        },
      }"
  />
</template>
```

Usage

```
import { Toaster } from '@/components/ui/toast' //route to toaster you created earlier


...
<Toaster/>
<Button @click="() => toast(Title)">Show Toast</Button>
...
```

Result

![image](https://github.com/user-attachments/assets/0f57f19c-0ace-457e-b64a-ccf9fa623f7e)

**Comment by IVoyt** [comment]
> @IVoyt Hey. You can set custom width for the toast using toastOptions.
> 
> If you wont to keept it static for all toast, you can just create your by importing it from the plugin, modify it using toastOptions, and when using it, import toaster from this file, not from the plugin, so :
> 
> ```
> <script setup lang="ts">
> import { Toaster } from 'vue-sonner'
> 
> 
> </script>
> <template>
>   <Toaster
>       :toastOptions="{
>         style :  { width: '150px' },
>       }"
>   />
> </template>
> ```
> 
> For tailwind
> 
> ```
> <script setup lang="ts">
> import { Toaster } from 'vue-sonner'
> 
> </script>
> <template>
>   <Toaster
>       :toastOptions="{
>         unstyled: true,
>         classes: {
>           toast: 'w-[150px]',
>         },
>       }"
>   />
> </template>
> ```
> 
> Usage
> 
> ```
> import { Toaster } from '@/components/ui/toast' //route to toaster you created earlier
> 
> 
> ...
> <Toaster/>
> <Button @click="() => toast(Title)">Show Toast</Button>
> ...
> ```
> 
> Result
> 
> ![image](https://private-user-images.githubusercontent.com/92380415/365203596-0f57f19c-0ace-457e-b64a-ccf9fa623f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM2ODcsIm5iZiI6MTcyNTYzMzM4NywicGF0aCI6Ii85MjM4MDQxNS8zNjUyMDM1OTYtMGY1N2YxOWMtMGFjZS00NTdlLWI2NGEtY2NmOWZhNjIzZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWQ2Y2MxMThlOWE5OWY3MGIxYzJlZmRlZmZlMTliNDAwNGFmYTYxZmZjMmE4OGM4M2I0NDBlNzA5ODBkN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAayHUHbtF6fdEwyatYssEGaBb4H_MsihiN0E82DsqA)

Thanks for your response.

I just tested and I see it is reactive. Perfect!

But I thought I can use this approach to set different widths for different toasts. I expected by changing width for every triggering toast it will not override width for all toasts but apply different width for different toasts. Is there a way to implement my approach?

**Comment by fdsssawe** [comment]
> > @IVoyt Hey. You can set custom width for the toast using toastOptions.
> > If you wont to keept it static for all toast, you can just create your by importing it from the plugin, modify it using toastOptions, and when using it, import toaster from this file, not from the plugin, so :
> > ```
> > <script setup lang="ts">
> > import { Toaster } from 'vue-sonner'
> > 
> > 
> > </script>
> > <template>
> >   <Toaster
> >       :toastOptions="{
> >         style :  { width: '150px' },
> >       }"
> >   />
> > </template>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For tailwind
> > ```
> > <script setup lang="ts">
> > import { Toaster } from 'vue-sonner'
> > 
> > </script>
> > <template>
> >   <Toaster
> >       :toastOptions="{
> >         unstyled: true,
> >         classes: {
> >           toast: 'w-[150px]',
> >         },
> >       }"
> >   />
> > </template>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usage
> > ```
> > import { Toaster } from '@/components/ui/toast' //route to toaster you created earlier
> > 
> > 
> > ...
> > <Toaster/>
> > <Button @click="() => toast(Title)">Show Toast</Button>
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Result
> > ![image](https://private-user-images.githubusercontent.com/92380415/365203596-0f57f19c-0ace-457e-b64a-ccf9fa623f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM2ODcsIm5iZiI6MTcyNTYzMzM4NywicGF0aCI6Ii85MjM4MDQxNS8zNjUyMDM1OTYtMGY1N2YxOWMtMGFjZS00NTdlLWI2NGEtY2NmOWZhNjIzZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE0MzYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWQ2Y2MxMThlOWE5OWY3MGIxYzJlZmRlZmZlMTliNDAwNGFmYTYxZmZjMmE4OGM4M2I0NDBlNzA5ODBkN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DAayHUHbtF6fdEwyatYssEGaBb4H_MsihiN0E82DsqA)
> 
> Thanks for your response.
> 
> I just tested and I see it is reactive. Perfect!
> 
> But I thought I can use this approach to set different widths for different toasts. I expected by changing width for every triggering toast it will not override width for all toasts but apply different width for different toasts. Is there a way to implement my approach?

@IVoyt Yep. On function call :

```
toast('Event has been created', {
  style: {
    width : '150px',
  },
})
```

using tailwind

```
toast('Hello World', {
  unstyled: true,
  classes: {
    toast: 'w-[150px]',
  }
})
```

**Comment by IVoyt** [comment]
I don't have tailwind and yet I need to figure out how to integrate within my project :)

Anyways many thanks!

**Comment by fdsssawe** [comment]
@IVoyt 

```
toast('Event has been created', {
  style: {
    width : '150px',
  },
})
```

this verison do not require tailwind.

**Comment by IVoyt** [comment]
> @IVoyt
> 
> ```
> toast('Event has been created', {
>   style: {
>     width : '150px',
>   },
> })
> ```
> 
> this verison do not require tailwind.

That worked, thanks a lot!

**Comment by fdsssawe** [comment]
> > @IVoyt
> > ```
> > toast('Event has been created', {
> >   style: {
> >     width : '150px',
> >   },
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this verison do not require tailwind.
> 
> That worked, thanks a lot!

Радий що зміг допомогти )

**Comment by d3vsparr0w** [comment]
If anyone uses `position="bottom-right"`, they might encounter an issue where the right margin doesn't align with the edge.
Try using this CSS:
```css
:where([data-sonner-toaster]) {
  --width: 240px !important;
}
``` 
240px is the desired width.

**Comment by mtzrmzia** [comment]
> If anyone uses `position="bottom-right"`, they might encounter an issue where the right margin doesn't align with the edge. Try using this CSS:
> 
> :where([data-sonner-toaster]) {
>   --width: 240px !important;
> }
> 240px is the desired width.

@d3vsparr0w  I am having this problem, but your solution doesn't work for me or I don't know how to apply it. Can you help me?
