### ISSUE TITLE
Unstyled classes not applying properly in 1.2.0

### ISSUE THREAD

**Issue by benjivm** [xiaoluoboding/vue-sonner#88]
No custom styles are applied in latest version. The following works in `v1.1.4` without issue, but does not work in `v1.2.0`:

```vue
<Toaster
    position="top-right"
    :toast-options="{
        unstyled: true,
        classes: {
            toast: 'w-full px-4 py-3 rounded-md !font-normal text-sm bg-white !border shadow',
            description: 'text-gray-500 text-sm',
        },
    }"
/>
```

**Comment by piercegearhart** [comment]
I am also experiencing this, the only one that is applying for me is title

**Comment by sadeghbarati** [comment]
Hi, can you guys provide a minimal reproduction?

**Comment by benjivm** [comment]
I created a blank Vue/tailwindcss app and cannot reproduce this; the styles are applied normally. In my large codebase with many styles the styles are applied as expected on versions < 1.2.0, and break in versions > 1.2.0. I am not entirely sure why this is the case, but I will investigate further.
