### ISSUE TITLE
Adding vue-sonner to ecosystem CI ?

### ISSUE THREAD

**Issue by adrienZ** [xiaoluoboding/vue-sonner#94]
Hi @xiaoluoboding, nice lib you got there ! 

would you consider adding vue-sonner to ecosystem-ci https://github.com/vuejs/ecosystem-ci ?

It would prevent unwanted regression.

I'm happy to help if necessary :)

**Comment by xiaoluoboding** [comment]
PRs welcome

**Comment by xiaoluoboding** [comment]
Thanks @adrienZ https://github.com/xiaoluoboding/vue-sonner/releases/tag/v1.2.3
